# Configuracion de Base de Datos para SQL Server 2022
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost;databaseName=gestion_productos;encrypt=true;trustServerCertificate=true;
db.user=usr_productos
db.password=Pass1234!

# Configuracion alternativa para MySQL (en caso de evaluacion en MySQL)
# db.driver=com.mysql.cj.jdbc.Driver
# db.url=jdbc:mysql://localhost:3306/gestion_productos?useSSL=false&serverTimezone=UTC
# db.user=root
# db.password=
